### ISSUE TITLE
CountingBloomFilter can't delet 

### ISSUE THREAD

**Issue by yelllowhat** [francois/hadoop-bloomfilter#1]
```
   run test case like this :

@Test
public void testBasics() {
    final CountingBloomFilter cbf = new CountingBloomFilter(100, 2,
            Hash.MURMUR_HASH);

        // ready to add 100 market 
    for (int i = 0; i < 100; i++) {
        Key key = new Key(("abc" + i).getBytes(UTF8));
        cbf.add(key);
    }

          // find and remove 
    for (int i = 0; i < 100; i++) {
        Key key = new Key(("abc" + i).getBytes(UTF8));
        assertTrue("key present after insertion", cbf.membershipTest(key));

        cbf.delete(key);
        assertFalse("key gone after deletion", cbf.membershipTest(key));
    }
}

 result : 

java.lang.AssertionError: key gone after deletion
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertFalse(Assert.java:64)
at org.apache.hadoop.util.bloom.CountingBloomFilterTest.testBasics(CountingBloomFilterTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
```

**Comment by francois** [comment]
I lifted the code from Hadoop. I don't really know if that's the expected behavior. My guess would be that since Bloom Filters are probabilistic in nature, it may be possible for the hash to remember a key that should have been deleted.

**Comment by yelllowhat** [comment]
Thanks for your reply, I may be not clear, we test, adding 10 elements, and then delete the 10 elements, followed by testing whether to delete, delete is the impact on the other elements.

```
@Test
public void testBasics() {
    final CountingBloomFilter cbf = new CountingBloomFilter(10, 2,
            Hash.MURMUR_HASH);

    for (int i = 0; i < 10; i++) {
        Key key = new Key(("abc" + i).getBytes(UTF8));
        cbf.add(key);
    }

    String keyStr = null;
    for (int i = 0; i < 10; i++) {
        keyStr = "abc" + i;
        Key key = new Key(keyStr.getBytes(UTF8));
        //assertTrue("key present after insertion", cbf.membershipTest(key));
        System.out.println("delete before , member ship test key : " + keyStr + " , " + cbf.membershipTest(key));

        cbf.delete(key);
        //assertFalse("key gone after deletion", cbf.membershipTest(key));
        System.out.println("delete after , member ship test key : " + keyStr + " , " + cbf.membershipTest(key));
    }
}
```

   result :+1: 

delete before , member ship test key : abc0 , true
delete after , member ship test key : abc0 , true
delete before , member ship test key : abc1 , true
delete after , member ship test key : abc1 , true
delete before , member ship test key : abc2 , true
delete after , member ship test key : abc2 , true
delete before , member ship test key : abc3 , true
delete after , member ship test key : abc3 , false
delete before , member ship test key : abc4 , true
delete after , member ship test key : abc4 , true
delete before , member ship test key : abc5 , true
delete after , member ship test key : abc5 , false
delete before , member ship test key : abc6 , true
delete after , member ship test key : abc6 , false
delete before , member ship test key : abc7 , true
delete after , member ship test key : abc7 , true
delete before , member ship test key : abc8 , true
delete after , member ship test key : abc8 , false
delete before , member ship test key : abc9 , true
delete after , member ship test key : abc9 , false

Why add to delete, the added value is still? Delete and also for other results have error influence ?

for example 

delete before , member ship test key : abc0 , true
delete after , member ship test key : abc0 , true
........

The correct result should be like this, to join the deleted, again looking for should return false, it returns the true here, said there was no real delete !
